'use client';

import { useEffect, useState } from 'react';

type Customer = { id:string; name:string; status:string; phone?:string|null; email?:string|null; leadScore?:number|null };
type Conversation = { id:string; status:string; priority:number; subject?:string|null; customer:Customer; channel?:{name:string;type:string}|null; messages?:Array<{content:string;direction:string;createdAt:string}> };
type Lead = { id:string; stage:string; value?:number|null; probability?:number|null; customer:Customer; owner?:{name:string}|null };
type Task = { id:string; title:string; status:string; priority:number; dueAt?:string|null; customer?:Customer|null; assignee?:{name:string}|null };
type Dashboard = { customers:number; conversations:number; followUps:number; activeLeads:number; openChats:number; hotLeadsNeedingFollowUp:number };
type OrynEvent = { id:string; name:string; occurredAt:string; payload:Record<string,unknown> };

const nav = [['⌂','Dashboard'],['◉','Inbox'],['♙','Customers'],['◆','Leads'],['↗','Sales'],['↻','Follow Up'],['✦','AI'],['⚡','Automation'],['▥','Analytics']];
const API = process.env.NEXT_PUBLIC_API_URL ?? 'http://localhost:4000';

export default function Home(){
  const [active,setActive]=useState('Dashboard'); const [token,setToken]=useState(''); const [me,setMe]=useState<any>(null); const [error,setError]=useState('');
  useEffect(()=>{setToken(localStorage.getItem('oryn_token')??'')},[]);
  useEffect(()=>{if(!token)return; fetch(`${API}/api/v1/auth/me`,{headers:{Authorization:`Bearer ${token}`}}).then(r=>r.ok?r.json():Promise.reject()).then(x=>setMe(x.data)).catch(()=>{localStorage.removeItem('oryn_token');setToken('')})},[token]);
  if(!token) return <Login onLogin={t=>{localStorage.setItem('oryn_token',t);setToken(t)}}/>;
  const logout=()=>{localStorage.removeItem('oryn_token');setToken('');setMe(null)};
  return <main className="shell"><aside className="sidebar"><div className="brand"><div className="logoMark">◢</div><div><div className="brandName">ORYN</div><div className="brandTag">Intelligent Customer Operations</div></div></div><div className="workspace"><span className="dot"/> ORYN Demo <span>⌄</span></div><nav>{nav.map(([icon,label])=><button key={label} className={active===label?'nav active':'nav'} onClick={()=>setActive(label)}><span>{icon}</span>{label}</button>)}</nav><div className="sidebarBottom"><button className="nav" onClick={logout}><span>↪</span>Sign out</button><div className="user"><div className="avatar">{(me?.name??'O').charAt(0)}</div><div><b>{me?.name??'ORYN Owner'}</b><small>{me?.role??'Owner'}</small></div></div></div></aside><section className="content"><header className="topbar"><div><div className="crumb">ORYN / {active}</div><h1>{active}</h1></div><div className="topActions"><button className="iconBtn">⌕</button><button className="iconBtn">♢</button><button className="primary" onClick={()=>setActive('Customers')}>＋ New Customer</button></div></header><Workspace active={active} token={token} setActive={setActive} error={error} setError={setError}/></section></main>
}

function Login({onLogin}:{onLogin:(token:string)=>void}){const [email,setEmail]=useState('admin@oryn.local');const [password,setPassword]=useState('oryn-demo-password');const [busy,setBusy]=useState(false);const [error,setError]=useState('');const submit=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);setError('');try{const r=await fetch(`${API}/api/v1/auth/login`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({organizationId:'org_demo',email,password})});const x=await r.json();if(!r.ok)throw new Error(x.error??'Login gagal');onLogin(x.data.token)}catch(e){setError(e instanceof Error?e.message:'Login gagal')}finally{setBusy(false)}};return <main className="loginShell"><form className="loginCard" onSubmit={submit}><div className="logoMark">◢</div><h1>ORYN</h1><p>Intelligent Customer Operations</p>{error&&<div className="errorBanner">⚠ {error}</div>}<label>Email<input value={email} onChange={e=>setEmail(e.target.value)} type="email" autoComplete="username"/></label><label>Password<input value={password} onChange={e=>setPassword(e.target.value)} type="password" autoComplete="current-password"/></label><button className="primary loginBtn" disabled={busy}>{busy?'Signing in…':'Sign in to ORYN'}</button><small>Demo workspace · org_demo</small></form></main>}

function Workspace({active,token,setActive,error,setError}:{active:string;token:string;setActive:(x:string)=>void;error:string;setError:(x:string)=>void}){const [dashboard,setDashboard]=useState<Dashboard|null>(null);const [customers,setCustomers]=useState<Customer[]>([]);const [conversations,setConversations]=useState<Conversation[]>([]);const [leads,setLeads]=useState<Lead[]>([]);const [tasks,setTasks]=useState<Task[]>([]);const [selected,setSelected]=useState<Conversation|null>(null);const [messages,setMessages]=useState<any[]>([]);const [draft,setDraft]=useState('');const [live,setLive]=useState(false);const headers={Authorization:`Bearer ${token}`};const get=async(path:string)=>{const r=await fetch(`${API}${path}`,{headers});if(!r.ok)throw new Error((await r.json()).error??'API error');return r.json()};const refresh=async()=>{try{setError('');const [d,c,i,l,f]=await Promise.all([get('/api/v1/dashboard'),get('/api/v1/customers?limit=50'),get('/api/v1/conversations?limit=50'),get('/api/v1/leads?limit=50'),get('/api/v1/follow-ups')]);setDashboard(d.data);setCustomers(c.data);setConversations(i.data);setLeads(l.data);setTasks(f.data)}catch(e){setError(e instanceof Error?e.message:'Gagal memuat data')}};
  useEffect(()=>{refresh()},[token]);
  useEffect(()=>{if(!selected)return;get(`/api/v1/conversations/${selected.id}/messages`).then(x=>setMessages(x.data)).catch(e=>setError(e.message))},[selected]);
  useEffect(()=>{if(!token)return;const controller=new AbortController();let stopped=false;let retry=500;let lastEventId='';let timer:ReturnType<typeof setTimeout>|undefined;let refreshTimer:ReturnType<typeof setTimeout>|undefined;
    const scheduleRefresh=()=>{if(refreshTimer)return;refreshTimer=setTimeout(()=>{refreshTimer=undefined;void refresh()},250)};
    const consume=async()=>{try{const h:Record<string,string>={Authorization:`Bearer ${token}`,'Accept':'text/event-stream'};if(lastEventId)h['Last-Event-ID']=lastEventId;const response=await fetch(`${API}/api/v1/events/stream`,{headers:h,signal:controller.signal,cache:'no-store'});if(!response.ok)throw new Error(`SSE ${response.status}`);if(!response.body)throw new Error('SSE stream unavailable');setLive(true);retry=500;const reader=response.body.getReader();const decoder=new TextDecoder();let buffer='';while(!stopped){const {value,done}=await reader.read();if(done)break;buffer+=decoder.decode(value,{stream:true});const frames=buffer.split(/\n\n/);buffer=frames.pop()??'';for(const frame of frames){let id='';let event='message';let data='';for(const line of frame.split(/\r?\n/)){if(line.startsWith('id:'))id=line.slice(3).trim();else if(line.startsWith('event:'))event=line.slice(6).trim();else if(line.startsWith('data:'))data+=line.slice(5).trim();}if(id)lastEventId=id;if(data&&event!=='heartbeat'){try{const parsed=JSON.parse(data) as OrynEvent;if(parsed.id)lastEventId=parsed.id;scheduleRefresh()}catch{}}}}}catch(e){if(!stopped&&!controller.signal.aborted){setLive(false);timer=setTimeout(consume,retry);retry=Math.min(retry*2,10000)}}};void consume();return()=>{stopped=true;controller.abort();if(timer)clearTimeout(timer);if(refreshTimer)clearTimeout(refreshTimer);setLive(false)}},[token]);
  const send=async()=>{if(!selected||!draft.trim())return;const r=await fetch(`${API}/api/v1/conversations/${selected.id}/messages`,{method:'POST',headers:{...headers,'content-type':'application/json'},body:JSON.stringify({content:draft,direction:'OUTBOUND',senderType:'user'})});if(!r.ok){setError('Pesan gagal dikirim');return}setDraft('');const x=await get(`/api/v1/conversations/${selected.id}/messages`);setMessages(x.data);refresh()};if(active==='Inbox')return <Inbox conversations={conversations} selected={selected} setSelected={setSelected} messages={messages} draft={draft} setDraft={setDraft} send={send} error={error} live={live}/>;if(active==='Customers')return <List title="Customers" subtitle="Customer 360 workspace" rows={customers} columns={['Customer','Status','Phone','AI Score']} render={c=><><div className="avatar">{c.name.charAt(0)}</div><div className="grow"><b>{c.name}</b><span>{c.email??'No email'}</span></div><span className="pill">{c.status.replaceAll('_',' ')}</span><span className="score">AI {c.leadScore??'—'}</span></>}/>;if(active==='Leads'||active==='Sales')return <List title={active} subtitle="Pipeline and revenue opportunities" rows={leads} columns={['Lead','Stage','Value','Owner']} render={l=><><div className="avatar">{l.customer.name.charAt(0)}</div><div className="grow"><b>{l.customer.name}</b><span>Probability {l.probability??0}%</span></div><span className="pill">{l.stage}</span><span className="score">{l.value?`Rp ${Number(l.value).toLocaleString('id-ID')}`:'—'}</span><span className="ownerText">{l.owner?.name??'Unassigned'}</span></>}/>;if(active==='Follow Up')return <List title="Follow Up" subtitle="Prioritized customer actions" rows={tasks} columns={['Task','Status','Due','Customer']} render={t=><><div className="avatar">↻</div><div className="grow"><b>{t.title}</b><span>Priority {t.priority}</span></div><span className="pill">{t.status}</span><span className="due">{t.dueAt?new Date(t.dueAt).toLocaleString('id-ID'):'No due date'}</span><span>{t.customer?.name??'—'}</span></>}/>;return <DashboardView dashboard={dashboard} customers={customers} setActive={setActive} error={error} live={live}/>}

function DashboardView({dashboard,customers,setActive,error,live}:{dashboard:Dashboard|null;customers:Customer[];setActive:(x:string)=>void;error:string;live:boolean}){const stats=dashboard?[['Total Pelanggan',dashboard.customers.toLocaleString('id-ID'),'♙'],['Chat Aktif',dashboard.openChats.toLocaleString('id-ID'),'◉'],['Follow Up',dashboard.followUps.toLocaleString('id-ID'),'↻'],['Lead Aktif',dashboard.activeLeads.toLocaleString('id-ID'),'↗']]:[];return <div className="dashboard">{error&&<div className="errorBanner">⚠ {error}</div>}<section className="hero"><div><div className="eyebrow">INTELLIGENT CUSTOMER OPERATIONS</div><h2>Semua pelanggan.<br/><span>Satu kendali.</span></h2><p>Kelola percakapan, follow-up, penjualan, dan insight pelanggan dalam satu pusat operasi yang diperkuat AI.</p><button className="heroBtn" onClick={()=>setActive('Inbox')}>Buka ORYN Inbox →</button></div><div className="heroOrb"><div className="orbCore">◢</div></div></section><div className="stats">{stats.map(([label,value,icon])=><Stat key={label} label={label} value={value} icon={icon}/>)}</div><div className="grid2"><section className="card"><div className="cardHead"><div><h3>AI Insight</h3><p>Prioritas yang ditemukan ORYN</p></div><span className="aiBadge">✦ AI</span></div><div className="insight"><div className="insightIcon">🔥</div><div><b>{dashboard?.hotLeadsNeedingFollowUp??'—'} pelanggan berpotensi tinggi perlu ditindaklanjuti.</b><p>Prioritas dihitung dari status dan lead score pelanggan.</p></div><button onClick={()=>setActive('Follow Up')}>Review →</button></div></section><section className="card"><div className="cardHead"><div><h3>Pelanggan Teratas</h3><p>Lead score tertinggi</p></div><button className="textBtn" onClick={()=>setActive('Customers')}>Lihat semua →</button></div>{customers.slice(0,3).map(c=><div className="follow" key={c.id}><div className="avatar small">{c.name.charAt(0)}</div><div className="grow"><b>{c.name}</b><span>{c.status.replaceAll('_',' ')}</span></div><strong>AI {c.leadScore??'—'}</strong></div>)}</section></div></div>}
function Inbox({conversations,selected,setSelected,messages,draft,setDraft,send,error,live}:{conversations:Conversation[];selected:Conversation|null;setSelected:(x:Conversation|null)=>void;messages:any[];draft:string;setDraft:(x:string)=>void;send:()=>void;error:string;live:boolean}){return <div className="inboxPage">{error&&<div className="errorBanner">⚠ {error}</div>}<section className="card inboxList"><div className="cardHead"><div><h3>Conversations</h3><p>{conversations.length} conversations · priority sorted · <b>{live?'● Live':'○ Reconnecting'}</b></p></div></div>{conversations.map(c=><button key={c.id} className={`conversationItem ${selected?.id===c.id?'selected':''}`} onClick={()=>setSelected(c)}><div className="avatar">{c.customer.name.charAt(0)}</div><div className="grow"><b>{c.customer.name}</b><span>{c.messages?.[0]?.content??'No messages yet'}</span></div><span className="convMeta">{c.channel?.type??'WEB'}<br/>{c.status}</span></button>)}</section><section className="card chatPanel">{selected?<><div className="chatHead"><div className="avatar">{selected.customer.name.charAt(0)}</div><div className="grow"><b>{selected.customer.name}</b><span>{selected.channel?.name??'Customer conversation'} · {selected.status}</span></div><span className="score">Priority {selected.priority}</span></div><div className="messages">{messages.map(m=><div key={m.id} className={`bubble ${m.direction==='OUTBOUND'?'out':''}`}><span>{m.content}</span><small>{new Date(m.createdAt).toLocaleTimeString('id-ID',{hour:'2-digit',minute:'2-digit'})}</small></div>)}</div><div className="composer"><input value={draft} onChange={e=>setDraft(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')send()}} placeholder="Tulis balasan…"/><button className="primary" onClick={send}>Kirim</button></div></>:<div className="empty chatEmpty">Pilih percakapan untuk mulai bekerja.</div>}</section></div>}
function List({title,subtitle,rows,columns,render}:{title:string;subtitle:string;rows:any[];columns:string[];render:(x:any)=>React.ReactNode}){return <div className="dashboard"><section className="card"><div className="cardHead"><div><h3>{title}</h3><p>{subtitle} · {rows.length} records</p></div></div><div className="listHead">{columns.map(c=><span key={c}>{c}</span>)}</div><div className="table">{rows.map(x=><div className="row" key={x.id}>{render(x)}</div>)}{!rows.length&&<div className="empty">Belum ada data.</div>}</div></section></div>}
function Stat({label,value,icon}:{label:string;value:string;icon:string}){return <div className="stat"><div className="statIcon">{icon}</div><span>{label}</span><strong>{value}</strong><small>• Live</small></div>}
